# 01 · Download and preprocess AERONET AOD Level 2.0 (Version 3)

**What this notebook does**

1. **Download** the NASA AERONET bulk archive (`.tar.gz`) into `DATA/RAW/` if it is not already there, extract it, and delete the archive.
2. **Read** every station file (`*.lev20`, one per AERONET site) and **merge** them into a single `pandas.DataFrame`.
3. **Export** one agent-ready Parquet table to `DATA/PROCESSED/`.

**Dataset**: AERONET **AOD Level 2.0** (cloud-screened *and* quality-assured), **Version 3**, **Daily averages**, all sites —
`https://aeronet.gsfc.nasa.gov/data_push/V3/AOD/AOD_Level20_Daily_V3.tar.gz` (~110 MB archive → ~570 MB extracted, ~1,485 sites, one row per site × day).

In [1]:
from pathlib import Path
import re
import tarfile
import time

import numpy as np
import pandas as pd
import requests
from tqdm.auto import tqdm

/home/ubuntu/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
ARCHIVE = "AOD_Level20_Daily_V3.tar.gz"
URL = "https://aeronet.gsfc.nasa.gov/data_push/V3/AOD/" + ARCHIVE

In [3]:
PROJECT_ROOT = Path.cwd().resolve()
if PROJECT_ROOT.name == "process_data":          # this notebook lives in notebooks/process_data/
    PROJECT_ROOT = PROJECT_ROOT.parent.parent

In [4]:
RAW_DIR       = PROJECT_ROOT / "DATA" / "RAW"
PROCESSED_DIR = PROJECT_ROOT / "DATA" / "PROCESSED"
RAW_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [5]:
TARBALL     = RAW_DIR / ARCHIVE                                  # deleted after extraction
EXTRACT_DIR = RAW_DIR / ARCHIVE.replace(".tar.gz", "")           # station files land here
OUT_PARQUET = PROCESSED_DIR / "AERONET_AOD_L2_Daily_V3.parquet"

In [6]:
print(f"URL          : {URL}")
print(f"PROJECT_ROOT : {PROJECT_ROOT}")
print(f"EXTRACT_DIR  : {EXTRACT_DIR}")
print(f"OUT_PARQUET  : {OUT_PARQUET}")

URL          : https://aeronet.gsfc.nasa.gov/data_push/V3/AOD/AOD_Level20_Daily_V3.tar.gz
PROJECT_ROOT : /home/ubuntu/ai_for_aeronet
EXTRACT_DIR  : /home/ubuntu/ai_for_aeronet/DATA/RAW/AOD_Level20_Daily_V3
OUT_PARQUET  : /home/ubuntu/ai_for_aeronet/DATA/PROCESSED/AERONET_AOD_L2_Daily_V3.parquet

## 1 · Download (if needed) → extract → delete the archive

In [7]:
def download(url: str, dest: Path, chunk_size: int = 1 << 20) -> None:
    tmp = dest.with_name(dest.name + ".part")
    with requests.get(url, stream=True, timeout=120) as r:
        r.raise_for_status()
        total = int(r.headers.get("Content-Length", 0)) or None
        with open(tmp, "wb") as fh, tqdm(total=total, unit="B", unit_scale=True, desc=dest.name) as bar:
            for part in r.iter_content(chunk_size):
                fh.write(part)
                bar.update(len(part))
    tmp.replace(dest)


def extract_tar_gz(archive: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    with tarfile.open(archive, "r:gz") as tf:
        try:
            tf.extractall(dest, filter="data")      
        except TypeError:                    
            tf.extractall(dest)


station_files = sorted(EXTRACT_DIR.rglob("*.lev20")) if EXTRACT_DIR.exists() else []

if station_files:
    print(f"Already extracted: {len(station_files)} station files in {EXTRACT_DIR}  →  skipping download.")
else:
    if TARBALL.exists():
        print(f"Found {TARBALL.name} ({TARBALL.stat().st_size / 1e6:,.0f} MB)  →  skipping download.")
    else:
        print(f"Downloading {URL}")
        t0 = time.time()
        download(URL, TARBALL)
        print(f"  done in {time.time() - t0:,.0f} s  ({TARBALL.stat().st_size / 1e6:,.0f} MB)")

    print(f"Extracting → {EXTRACT_DIR}")
    extract_tar_gz(TARBALL, EXTRACT_DIR)
    TARBALL.unlink()
    print(f"Deleted {TARBALL.name}")
    station_files = sorted(EXTRACT_DIR.rglob("*.lev20"))

print(f"{len(station_files):,} station files ready")

Already extracted: 1485 station files in /home/ubuntu/ai_for_aeronet/DATA/RAW/AOD_Level20_Daily_V3  →  skipping download.
1,485 station files ready

## 2 · Read every station file and merge

Each `*.lev20` file is one AERONET site:

```
line 1  AERONET Version 3
line 2  <site name>
line 3  Version 3: AOD Level 2.0
line 4  (description)
line 5  Contact: PI=<name>; PI Email=<email>
line 6  Daily Averages,UNITS can be found at,,, https://aeronet.gsfc.nasa.gov/new_web/units.html
line 7  <CSV header>
line 8+ <CSV rows>, missing values are -999
```

In [8]:
MISSING = -999.0

def read_station(path: Path) -> pd.DataFrame:
    # Parse one AERONET .lev20 file -> DataFrame (raw AERONET column names, -999 -> NaN,
    # plus `site`, `PI`, `PI_Email` taken from the file header).
    with open(path, encoding="latin-1") as fh:
        header = [next(fh).rstrip("\n") for _ in range(6)]
    site = header[1].strip()
    m = re.search(r"PI=(.*?);\s*PI Email=(.*)", header[4])
    pi, pi_email = (m.group(1).strip(), m.group(2).strip()) if m else (None, None)

    df = pd.read_csv(path, skiprows=6, encoding="latin-1", low_memory=False)

    # -999 → NaN in every numeric column (count columns never contain -999, so they stay integer)
    num = df.select_dtypes("number").columns
    df[num] = df[num].mask(df[num] == MISSING)

    df.insert(0, "site", site)
    df["PI"] = pi
    df["PI_Email"] = pi_email
    return df


frames, failures = [], []
t0 = time.time()
for p in tqdm(station_files, desc="Reading stations"):
    try:
        frames.append(read_station(p))
    except Exception as exc:            
        failures.append((p.name, repr(exc)))

aeronet_raw = pd.concat(frames, ignore_index=True)
del frames

print(f"Merged {len(station_files) - len(failures):,} stations → {aeronet_raw.shape[0]:,} rows × {aeronet_raw.shape[1]} columns "
      f"in {time.time() - t0:,.0f} s")
if failures:
    print(f"\n{len(failures)} file(s) failed to parse:")
    for name, err in failures:
        print(f"  {name}: {err}")

Reading stations:   0%|          | 0/1485 [00:00<?, ?it/s]

Reading stations:   0%|          | 4/1485 [00:00<00:38, 38.10it/s]

Reading stations:   1%|          | 9/1485 [00:00<00:34, 43.31it/s]

Reading stations:   1%|          | 14/1485 [00:00<00:32, 45.85it/s]

Reading stations:   1%|▏         | 19/1485 [00:00<00:43, 34.08it/s]

Reading stations:   2%|▏         | 25/1485 [00:00<00:37, 39.09it/s]

Reading stations:   2%|▏         | 30/1485 [00:00<00:36, 40.02it/s]

Reading stations:   2%|▏         | 35/1485 [00:00<00:34, 42.64it/s]

Reading stations:   3%|▎         | 40/1485 [00:00<00:34, 41.92it/s]

Reading stations:   3%|▎         | 45/1485 [00:01<00:37, 37.96it/s]

Reading stations:   3%|▎         | 50/1485 [00:01<00:36, 39.53it/s]

Reading stations:   4%|▎         | 55/1485 [00:01<00:37, 37.89it/s]

Reading stations:   4%|▍         | 62/1485 [00:01<00:31, 44.67it/s]

Reading stations:   5%|▍         | 68/1485 [00:01<00:29, 47.72it/s]

Reading stations:   5%|▍         | 73/1485 [00:01<00:33, 41.93it/s]

Reading stations:   5%|▌         | 78/1485 [00:01<00:37, 37.07it/s]

Reading stations:   6%|▌         | 82/1485 [00:02<00:39, 35.92it/s]

Reading stations:   6%|▌         | 86/1485 [00:02<00:40, 34.20it/s]

Reading stations:   6%|▌         | 90/1485 [00:02<00:39, 35.49it/s]

Reading stations:   6%|▋         | 94/1485 [00:02<00:42, 32.42it/s]

Reading stations:   7%|▋         | 98/1485 [00:02<00:42, 32.84it/s]

Reading stations:   7%|▋         | 102/1485 [00:02<00:48, 28.62it/s]

Reading stations:   7%|▋         | 106/1485 [00:02<00:51, 26.99it/s]

Reading stations:   7%|▋         | 109/1485 [00:03<00:50, 27.27it/s]

Reading stations:   8%|▊         | 113/1485 [00:03<00:47, 28.76it/s]

Reading stations:   8%|▊         | 117/1485 [00:03<00:46, 29.27it/s]

Reading stations:   8%|▊         | 122/1485 [00:03<00:43, 31.19it/s]

Reading stations:   8%|▊         | 126/1485 [00:03<00:46, 29.02it/s]

Reading stations:   9%|▉         | 130/1485 [00:03<00:46, 28.92it/s]

Reading stations:   9%|▉         | 135/1485 [00:03<00:41, 32.80it/s]

Reading stations:   9%|▉         | 139/1485 [00:04<00:46, 28.91it/s]

Reading stations:  10%|▉         | 143/1485 [00:04<00:48, 27.87it/s]

Reading stations:  10%|▉         | 147/1485 [00:04<00:43, 30.52it/s]

Reading stations:  10%|█         | 151/1485 [00:04<00:41, 32.06it/s]

Reading stations:  10%|█         | 155/1485 [00:04<00:47, 27.99it/s]

Reading stations:  11%|█         | 160/1485 [00:04<00:41, 32.27it/s]

Reading stations:  11%|█         | 164/1485 [00:04<00:40, 32.38it/s]

Reading stations:  11%|█▏        | 169/1485 [00:04<00:37, 34.86it/s]

Reading stations:  12%|█▏        | 174/1485 [00:05<00:38, 34.29it/s]

Reading stations:  12%|█▏        | 178/1485 [00:05<00:42, 30.92it/s]

Reading stations:  12%|█▏        | 183/1485 [00:05<00:36, 35.22it/s]

Reading stations:  13%|█▎        | 187/1485 [00:05<00:41, 31.61it/s]

Reading stations:  13%|█▎        | 192/1485 [00:05<00:39, 32.67it/s]

Reading stations:  13%|█▎        | 196/1485 [00:05<00:42, 30.43it/s]

Reading stations:  13%|█▎        | 200/1485 [00:06<00:52, 24.56it/s]

Reading stations:  14%|█▎        | 203/1485 [00:06<00:53, 24.17it/s]

Reading stations:  14%|█▍        | 206/1485 [00:06<00:52, 24.53it/s]

Reading stations:  14%|█▍        | 209/1485 [00:06<00:49, 25.71it/s]

Reading stations:  14%|█▍        | 212/1485 [00:06<00:53, 23.88it/s]

Reading stations:  15%|█▍        | 216/1485 [00:06<00:49, 25.39it/s]

Reading stations:  15%|█▍        | 220/1485 [00:06<00:43, 28.83it/s]

Reading stations:  15%|█▌        | 224/1485 [00:06<00:48, 25.85it/s]

Reading stations:  15%|█▌        | 229/1485 [00:07<00:40, 30.65it/s]

Reading stations:  16%|█▌        | 235/1485 [00:07<00:34, 36.75it/s]

Reading stations:  16%|█▌        | 241/1485 [00:07<00:30, 40.80it/s]

Reading stations:  17%|█▋        | 248/1485 [00:07<00:26, 46.55it/s]

Reading stations:  17%|█▋        | 255/1485 [00:07<00:24, 51.24it/s]

Reading stations:  18%|█▊        | 261/1485 [00:07<00:22, 53.57it/s]

Reading stations:  18%|█▊        | 267/1485 [00:07<00:22, 54.30it/s]

Reading stations:  18%|█▊        | 273/1485 [00:07<00:24, 49.17it/s]

Reading stations:  19%|█▉        | 279/1485 [00:08<00:28, 42.54it/s]

Reading stations:  19%|█▉        | 284/1485 [00:08<00:41, 29.16it/s]

Reading stations:  19%|█▉        | 288/1485 [00:08<00:40, 29.71it/s]

Reading stations:  20%|█▉        | 292/1485 [00:08<00:41, 28.94it/s]

Reading stations:  20%|██        | 297/1485 [00:08<00:36, 32.80it/s]

Reading stations:  20%|██        | 301/1485 [00:08<00:37, 31.50it/s]

Reading stations:  21%|██        | 305/1485 [00:09<00:36, 32.70it/s]

Reading stations:  21%|██        | 309/1485 [00:09<00:38, 30.47it/s]

Reading stations:  21%|██        | 313/1485 [00:09<00:42, 27.79it/s]

Reading stations:  21%|██▏       | 316/1485 [00:09<00:43, 27.17it/s]

Reading stations:  22%|██▏       | 320/1485 [00:09<00:41, 28.37it/s]

Reading stations:  22%|██▏       | 325/1485 [00:09<00:35, 32.48it/s]

Reading stations:  22%|██▏       | 330/1485 [00:09<00:34, 33.78it/s]

Reading stations:  22%|██▏       | 334/1485 [00:09<00:34, 33.71it/s]

Reading stations:  23%|██▎       | 339/1485 [00:10<00:32, 35.45it/s]

Reading stations:  23%|██▎       | 345/1485 [00:10<00:27, 40.81it/s]

Reading stations:  24%|██▎       | 352/1485 [00:10<00:24, 46.60it/s]

Reading stations:  24%|██▍       | 357/1485 [00:10<00:23, 47.39it/s]

Reading stations:  24%|██▍       | 363/1485 [00:10<00:22, 50.06it/s]

Reading stations:  25%|██▍       | 370/1485 [00:10<00:20, 53.22it/s]

Reading stations:  25%|██▌       | 376/1485 [00:10<00:20, 54.78it/s]

Reading stations:  26%|██▌       | 383/1485 [00:10<00:19, 56.60it/s]

Reading stations:  26%|██▋       | 390/1485 [00:10<00:18, 58.20it/s]

Reading stations:  27%|██▋       | 397/1485 [00:11<00:18, 59.10it/s]

Reading stations:  27%|██▋       | 404/1485 [00:11<00:18, 58.46it/s]

Reading stations:  28%|██▊       | 410/1485 [00:11<00:19, 56.48it/s]

Reading stations:  28%|██▊       | 416/1485 [00:11<00:18, 56.48it/s]

Reading stations:  28%|██▊       | 422/1485 [00:11<00:19, 54.60it/s]

Reading stations:  29%|██▉       | 428/1485 [00:11<00:20, 52.25it/s]

Reading stations:  29%|██▉       | 434/1485 [00:11<00:19, 53.50it/s]

Reading stations:  30%|██▉       | 440/1485 [00:11<00:19, 54.15it/s]

Reading stations:  30%|███       | 446/1485 [00:12<00:18, 54.96it/s]

Reading stations:  30%|███       | 452/1485 [00:12<00:18, 55.15it/s]

Reading stations:  31%|███       | 458/1485 [00:12<00:18, 56.39it/s]

Reading stations:  31%|███       | 464/1485 [00:12<00:17, 57.03it/s]

Reading stations:  32%|███▏      | 470/1485 [00:12<00:18, 56.25it/s]

Reading stations:  32%|███▏      | 476/1485 [00:12<00:17, 56.38it/s]

Reading stations:  33%|███▎      | 483/1485 [00:12<00:17, 58.05it/s]

Reading stations:  33%|███▎      | 489/1485 [00:12<00:25, 39.65it/s]

Reading stations:  33%|███▎      | 494/1485 [00:13<00:27, 36.70it/s]

Reading stations:  34%|███▎      | 499/1485 [00:13<00:28, 34.79it/s]

Reading stations:  34%|███▍      | 504/1485 [00:13<00:27, 35.53it/s]

Reading stations:  34%|███▍      | 509/1485 [00:13<00:26, 37.47it/s]

Reading stations:  35%|███▍      | 514/1485 [00:13<00:24, 40.38it/s]

Reading stations:  35%|███▍      | 519/1485 [00:13<00:27, 34.87it/s]

Reading stations:  35%|███▌      | 523/1485 [00:13<00:27, 35.46it/s]

Reading stations:  35%|███▌      | 527/1485 [00:14<00:29, 32.51it/s]

Reading stations:  36%|███▌      | 531/1485 [00:14<00:33, 28.27it/s]

Reading stations:  36%|███▌      | 535/1485 [00:14<00:34, 27.16it/s]

Reading stations:  36%|███▋      | 539/1485 [00:14<00:37, 25.44it/s]

Reading stations:  37%|███▋      | 543/1485 [00:14<00:39, 23.63it/s]

Reading stations:  37%|███▋      | 547/1485 [00:14<00:36, 25.79it/s]

Reading stations:  37%|███▋      | 550/1485 [00:15<00:48, 19.27it/s]

Reading stations:  37%|███▋      | 554/1485 [00:15<00:46, 19.85it/s]

Reading stations:  38%|███▊      | 558/1485 [00:15<00:40, 22.96it/s]

Reading stations:  38%|███▊      | 562/1485 [00:15<00:36, 25.61it/s]

Reading stations:  38%|███▊      | 566/1485 [00:15<00:35, 26.23it/s]

Reading stations:  38%|███▊      | 569/1485 [00:15<00:34, 26.78it/s]

Reading stations:  39%|███▊      | 572/1485 [00:15<00:34, 26.21it/s]

Reading stations:  39%|███▉      | 576/1485 [00:16<00:32, 28.03it/s]

Reading stations:  39%|███▉      | 580/1485 [00:16<00:36, 25.07it/s]

Reading stations:  39%|███▉      | 586/1485 [00:16<00:29, 30.16it/s]

Reading stations:  40%|███▉      | 590/1485 [00:16<00:30, 29.43it/s]

Reading stations:  40%|████      | 594/1485 [00:16<00:29, 29.81it/s]

Reading stations:  40%|████      | 598/1485 [00:16<00:30, 29.26it/s]

Reading stations:  41%|████      | 602/1485 [00:16<00:28, 30.50it/s]

Reading stations:  41%|████      | 606/1485 [00:17<00:32, 26.74it/s]

Reading stations:  41%|████      | 610/1485 [00:17<00:31, 28.08it/s]

Reading stations:  41%|████▏     | 614/1485 [00:17<00:29, 29.35it/s]

Reading stations:  42%|████▏     | 618/1485 [00:17<00:31, 27.52it/s]

Reading stations:  42%|████▏     | 624/1485 [00:17<00:25, 34.35it/s]

Reading stations:  42%|████▏     | 628/1485 [00:17<00:27, 31.46it/s]

Reading stations:  43%|████▎     | 632/1485 [00:17<00:26, 32.79it/s]

Reading stations:  43%|████▎     | 636/1485 [00:18<00:25, 32.69it/s]

Reading stations:  43%|████▎     | 640/1485 [00:18<00:26, 32.50it/s]

Reading stations:  43%|████▎     | 645/1485 [00:18<00:23, 35.56it/s]

Reading stations:  44%|████▎     | 649/1485 [00:18<00:24, 34.32it/s]

Reading stations:  44%|████▍     | 653/1485 [00:18<00:23, 34.93it/s]

Reading stations:  44%|████▍     | 657/1485 [00:18<00:23, 35.51it/s]

Reading stations:  45%|████▍     | 661/1485 [00:18<00:24, 33.01it/s]

Reading stations:  45%|████▍     | 665/1485 [00:18<00:27, 30.02it/s]

Reading stations:  45%|████▌     | 669/1485 [00:19<00:28, 28.81it/s]

Reading stations:  45%|████▌     | 672/1485 [00:19<00:30, 26.80it/s]

Reading stations:  45%|████▌     | 675/1485 [00:19<00:31, 25.49it/s]

Reading stations:  46%|████▌     | 679/1485 [00:19<00:31, 25.34it/s]

Reading stations:  46%|████▌     | 684/1485 [00:19<00:28, 28.60it/s]

Reading stations:  46%|████▋     | 687/1485 [00:19<00:33, 23.64it/s]

Reading stations:  46%|████▋     | 690/1485 [00:19<00:33, 23.79it/s]

Reading stations:  47%|████▋     | 693/1485 [00:20<00:37, 21.28it/s]

Reading stations:  47%|████▋     | 697/1485 [00:20<00:32, 23.98it/s]

Reading stations:  47%|████▋     | 702/1485 [00:20<00:27, 28.66it/s]

Reading stations:  48%|████▊     | 708/1485 [00:20<00:21, 35.33it/s]

Reading stations:  48%|████▊     | 712/1485 [00:20<00:21, 35.90it/s]

Reading stations:  48%|████▊     | 718/1485 [00:20<00:18, 41.07it/s]

Reading stations:  49%|████▊     | 723/1485 [00:20<00:17, 42.35it/s]

Reading stations:  49%|████▉     | 729/1485 [00:20<00:16, 46.01it/s]

Reading stations:  49%|████▉     | 734/1485 [00:21<00:16, 46.65it/s]

Reading stations:  50%|████▉     | 739/1485 [00:21<00:20, 35.72it/s]

Reading stations:  50%|█████     | 744/1485 [00:21<00:22, 33.45it/s]

Reading stations:  51%|█████     | 750/1485 [00:21<00:20, 35.45it/s]

Reading stations:  51%|█████     | 754/1485 [00:21<00:22, 32.68it/s]

Reading stations:  51%|█████     | 758/1485 [00:21<00:21, 33.71it/s]

Reading stations:  51%|█████▏    | 762/1485 [00:21<00:20, 34.45it/s]

Reading stations:  52%|█████▏    | 767/1485 [00:22<00:19, 36.86it/s]

Reading stations:  52%|█████▏    | 771/1485 [00:22<00:20, 34.64it/s]

Reading stations:  52%|█████▏    | 776/1485 [00:22<00:19, 37.08it/s]

Reading stations:  53%|█████▎    | 780/1485 [00:22<00:20, 34.85it/s]

Reading stations:  53%|█████▎    | 784/1485 [00:22<00:21, 32.74it/s]

Reading stations:  53%|█████▎    | 789/1485 [00:22<00:20, 34.20it/s]

Reading stations:  53%|█████▎    | 793/1485 [00:22<00:24, 27.79it/s]

Reading stations:  54%|█████▎    | 796/1485 [00:23<00:27, 24.98it/s]

Reading stations:  54%|█████▍    | 800/1485 [00:23<00:25, 27.25it/s]

Reading stations:  54%|█████▍    | 803/1485 [00:23<00:25, 27.26it/s]

Reading stations:  54%|█████▍    | 808/1485 [00:23<00:20, 32.53it/s]

Reading stations:  55%|█████▍    | 812/1485 [00:23<00:24, 27.76it/s]

Reading stations:  55%|█████▍    | 816/1485 [00:23<00:34, 19.39it/s]

Reading stations:  55%|█████▌    | 819/1485 [00:24<00:31, 20.89it/s]

Reading stations:  55%|█████▌    | 824/1485 [00:24<00:25, 25.80it/s]

Reading stations:  56%|█████▌    | 830/1485 [00:24<00:20, 32.51it/s]

Reading stations:  56%|█████▌    | 834/1485 [00:24<00:21, 30.43it/s]

Reading stations:  56%|█████▋    | 838/1485 [00:24<00:20, 31.35it/s]

Reading stations:  57%|█████▋    | 843/1485 [00:24<00:18, 35.40it/s]

Reading stations:  57%|█████▋    | 847/1485 [00:24<00:21, 29.10it/s]

Reading stations:  57%|█████▋    | 851/1485 [00:25<00:21, 29.17it/s]

Reading stations:  58%|█████▊    | 855/1485 [00:25<00:20, 30.80it/s]

Reading stations:  58%|█████▊    | 859/1485 [00:25<00:21, 29.33it/s]

Reading stations:  58%|█████▊    | 864/1485 [00:25<00:19, 32.11it/s]

Reading stations:  58%|█████▊    | 868/1485 [00:25<00:19, 32.30it/s]

Reading stations:  59%|█████▉    | 873/1485 [00:25<00:17, 35.78it/s]

Reading stations:  59%|█████▉    | 877/1485 [00:25<00:16, 36.56it/s]

Reading stations:  59%|█████▉    | 881/1485 [00:26<00:21, 27.61it/s]

Reading stations:  60%|█████▉    | 887/1485 [00:26<00:17, 33.87it/s]

Reading stations:  60%|██████    | 892/1485 [00:26<00:15, 37.50it/s]

Reading stations:  60%|██████    | 897/1485 [00:26<00:16, 35.87it/s]

Reading stations:  61%|██████    | 901/1485 [00:26<00:16, 35.12it/s]

Reading stations:  61%|██████    | 905/1485 [00:26<00:19, 29.22it/s]

Reading stations:  61%|██████    | 909/1485 [00:26<00:18, 31.30it/s]

Reading stations:  61%|██████▏   | 913/1485 [00:26<00:18, 30.37it/s]

Reading stations:  62%|██████▏   | 917/1485 [00:27<00:19, 28.67it/s]

Reading stations:  62%|██████▏   | 923/1485 [00:27<00:15, 35.34it/s]

Reading stations:  63%|██████▎   | 929/1485 [00:27<00:13, 40.28it/s]

Reading stations:  63%|██████▎   | 934/1485 [00:27<00:12, 42.73it/s]

Reading stations:  63%|██████▎   | 940/1485 [00:27<00:11, 45.86it/s]

Reading stations:  64%|██████▎   | 945/1485 [00:27<00:15, 34.79it/s]

Reading stations:  64%|██████▍   | 949/1485 [00:27<00:17, 31.07it/s]

Reading stations:  64%|██████▍   | 953/1485 [00:28<00:18, 28.30it/s]

Reading stations:  64%|██████▍   | 957/1485 [00:28<00:19, 27.53it/s]

Reading stations:  65%|██████▍   | 961/1485 [00:28<00:17, 29.27it/s]

Reading stations:  65%|██████▍   | 965/1485 [00:28<00:18, 27.85it/s]

Reading stations:  65%|██████▌   | 970/1485 [00:28<00:16, 31.09it/s]

Reading stations:  66%|██████▌   | 974/1485 [00:28<00:17, 29.82it/s]

Reading stations:  66%|██████▌   | 978/1485 [00:28<00:17, 29.34it/s]

Reading stations:  66%|██████▌   | 983/1485 [00:29<00:15, 33.45it/s]

Reading stations:  66%|██████▋   | 987/1485 [00:29<00:16, 30.02it/s]

Reading stations:  67%|██████▋   | 991/1485 [00:29<00:16, 30.68it/s]

Reading stations:  67%|██████▋   | 996/1485 [00:29<00:15, 32.19it/s]

Reading stations:  67%|██████▋   | 1000/1485 [00:29<00:15, 30.74it/s]

Reading stations:  68%|██████▊   | 1004/1485 [00:29<00:18, 26.54it/s]

Reading stations:  68%|██████▊   | 1007/1485 [00:29<00:18, 25.52it/s]

Reading stations:  68%|██████▊   | 1010/1485 [00:30<00:18, 25.15it/s]

Reading stations:  68%|██████▊   | 1013/1485 [00:30<00:19, 24.34it/s]

Reading stations:  68%|██████▊   | 1016/1485 [00:30<00:18, 25.27it/s]

Reading stations:  69%|██████▊   | 1019/1485 [00:30<00:18, 25.86it/s]

Reading stations:  69%|██████▉   | 1024/1485 [00:30<00:15, 30.08it/s]

Reading stations:  69%|██████▉   | 1029/1485 [00:30<00:13, 35.06it/s]

Reading stations:  70%|██████▉   | 1034/1485 [00:30<00:12, 35.48it/s]

Reading stations:  70%|██████▉   | 1038/1485 [00:30<00:12, 35.83it/s]

Reading stations:  70%|███████   | 1042/1485 [00:31<00:12, 36.07it/s]

Reading stations:  71%|███████   | 1047/1485 [00:31<00:11, 39.48it/s]

Reading stations:  71%|███████   | 1052/1485 [00:31<00:10, 39.61it/s]

Reading stations:  71%|███████   | 1057/1485 [00:31<00:10, 39.18it/s]

Reading stations:  72%|███████▏  | 1063/1485 [00:31<00:11, 37.09it/s]

Reading stations:  72%|███████▏  | 1068/1485 [00:31<00:10, 39.49it/s]

Reading stations:  72%|███████▏  | 1073/1485 [00:31<00:09, 41.73it/s]

Reading stations:  73%|███████▎  | 1078/1485 [00:31<00:09, 43.72it/s]

Reading stations:  73%|███████▎  | 1083/1485 [00:32<00:20, 19.91it/s]

Reading stations:  73%|███████▎  | 1088/1485 [00:32<00:16, 23.91it/s]

Reading stations:  74%|███████▎  | 1092/1485 [00:32<00:15, 25.47it/s]

Reading stations:  74%|███████▍  | 1097/1485 [00:32<00:13, 29.54it/s]

Reading stations:  74%|███████▍  | 1101/1485 [00:32<00:12, 30.44it/s]

Reading stations:  74%|███████▍  | 1105/1485 [00:33<00:15, 25.28it/s]

Reading stations:  75%|███████▍  | 1111/1485 [00:33<00:11, 32.06it/s]

Reading stations:  75%|███████▌  | 1115/1485 [00:33<00:11, 32.11it/s]

Reading stations:  75%|███████▌  | 1120/1485 [00:33<00:10, 34.27it/s]

Reading stations:  76%|███████▌  | 1124/1485 [00:33<00:10, 34.18it/s]

Reading stations:  76%|███████▌  | 1128/1485 [00:33<00:10, 34.22it/s]

Reading stations:  76%|███████▌  | 1132/1485 [00:33<00:10, 32.66it/s]

Reading stations:  76%|███████▋  | 1136/1485 [00:33<00:10, 32.63it/s]

Reading stations:  77%|███████▋  | 1142/1485 [00:34<00:08, 38.34it/s]

Reading stations:  77%|███████▋  | 1146/1485 [00:34<00:08, 38.56it/s]

Reading stations:  78%|███████▊  | 1151/1485 [00:34<00:08, 40.54it/s]

Reading stations:  78%|███████▊  | 1156/1485 [00:34<00:08, 39.59it/s]

Reading stations:  78%|███████▊  | 1161/1485 [00:34<00:09, 35.60it/s]

Reading stations:  78%|███████▊  | 1165/1485 [00:34<00:09, 33.79it/s]

Reading stations:  79%|███████▊  | 1169/1485 [00:34<00:11, 28.11it/s]

Reading stations:  79%|███████▉  | 1173/1485 [00:35<00:10, 29.81it/s]

Reading stations:  79%|███████▉  | 1177/1485 [00:35<00:11, 26.88it/s]

Reading stations:  80%|███████▉  | 1181/1485 [00:35<00:12, 24.51it/s]

Reading stations:  80%|███████▉  | 1185/1485 [00:35<00:11, 26.98it/s]

Reading stations:  80%|████████  | 1189/1485 [00:35<00:12, 24.60it/s]

Reading stations:  80%|████████  | 1193/1485 [00:35<00:10, 27.74it/s]

Reading stations:  81%|████████  | 1197/1485 [00:35<00:09, 29.85it/s]

Reading stations:  81%|████████  | 1201/1485 [00:36<00:09, 30.64it/s]

Reading stations:  81%|████████▏ | 1207/1485 [00:36<00:07, 37.17it/s]

Reading stations:  82%|████████▏ | 1211/1485 [00:36<00:07, 36.21it/s]

Reading stations:  82%|████████▏ | 1215/1485 [00:36<00:10, 25.61it/s]

Reading stations:  82%|████████▏ | 1221/1485 [00:36<00:08, 31.21it/s]

Reading stations:  82%|████████▏ | 1225/1485 [00:36<00:07, 32.64it/s]

Reading stations:  83%|████████▎ | 1229/1485 [00:36<00:08, 30.00it/s]

Reading stations:  83%|████████▎ | 1234/1485 [00:37<00:07, 33.67it/s]

Reading stations:  83%|████████▎ | 1238/1485 [00:37<00:07, 32.09it/s]

Reading stations:  84%|████████▎ | 1242/1485 [00:37<00:08, 30.01it/s]

Reading stations:  84%|████████▍ | 1246/1485 [00:37<00:08, 26.80it/s]

Reading stations:  84%|████████▍ | 1250/1485 [00:37<00:08, 27.02it/s]

Reading stations:  84%|████████▍ | 1253/1485 [00:37<00:08, 26.97it/s]

Reading stations:  85%|████████▍ | 1257/1485 [00:37<00:07, 28.86it/s]

Reading stations:  85%|████████▍ | 1260/1485 [00:38<00:09, 24.86it/s]

Reading stations:  85%|████████▌ | 1263/1485 [00:38<00:08, 24.72it/s]

Reading stations:  85%|████████▌ | 1266/1485 [00:38<00:08, 25.41it/s]

Reading stations:  85%|████████▌ | 1269/1485 [00:38<00:08, 25.79it/s]

Reading stations:  86%|████████▌ | 1273/1485 [00:38<00:07, 27.55it/s]

Reading stations:  86%|████████▌ | 1276/1485 [00:38<00:08, 25.54it/s]

Reading stations:  86%|████████▌ | 1279/1485 [00:38<00:09, 22.27it/s]

Reading stations:  86%|████████▋ | 1282/1485 [00:39<00:08, 23.69it/s]

Reading stations:  87%|████████▋ | 1286/1485 [00:39<00:07, 26.68it/s]

Reading stations:  87%|████████▋ | 1291/1485 [00:39<00:06, 32.31it/s]

Reading stations:  87%|████████▋ | 1295/1485 [00:39<00:05, 34.17it/s]

Reading stations:  87%|████████▋ | 1299/1485 [00:39<00:05, 32.80it/s]

Reading stations:  88%|████████▊ | 1305/1485 [00:39<00:04, 38.90it/s]

Reading stations:  88%|████████▊ | 1310/1485 [00:39<00:05, 34.81it/s]

Reading stations:  88%|████████▊ | 1314/1485 [00:39<00:05, 31.67it/s]

Reading stations:  89%|████████▉ | 1319/1485 [00:40<00:04, 34.49it/s]

Reading stations:  89%|████████▉ | 1323/1485 [00:40<00:05, 30.01it/s]

Reading stations:  89%|████████▉ | 1329/1485 [00:40<00:04, 34.41it/s]

Reading stations:  90%|████████▉ | 1333/1485 [00:40<00:04, 33.85it/s]

Reading stations:  90%|█████████ | 1338/1485 [00:40<00:03, 36.87it/s]

Reading stations:  90%|█████████ | 1342/1485 [00:40<00:04, 31.38it/s]

Reading stations:  91%|█████████ | 1346/1485 [00:40<00:04, 31.21it/s]

Reading stations:  91%|█████████ | 1350/1485 [00:41<00:04, 31.72it/s]

Reading stations:  91%|█████████ | 1354/1485 [00:41<00:04, 28.72it/s]

Reading stations:  91%|█████████▏| 1358/1485 [00:41<00:04, 28.30it/s]

Reading stations:  92%|█████████▏| 1361/1485 [00:41<00:04, 27.62it/s]

Reading stations:  92%|█████████▏| 1365/1485 [00:41<00:03, 30.11it/s]

Reading stations:  92%|█████████▏| 1369/1485 [00:41<00:03, 29.03it/s]

Reading stations:  92%|█████████▏| 1373/1485 [00:41<00:03, 28.67it/s]

Reading stations:  93%|█████████▎| 1377/1485 [00:41<00:03, 30.63it/s]

Reading stations:  93%|█████████▎| 1381/1485 [00:42<00:03, 32.49it/s]

Reading stations:  93%|█████████▎| 1385/1485 [00:42<00:03, 32.11it/s]

Reading stations:  94%|█████████▎| 1389/1485 [00:42<00:03, 31.59it/s]

Reading stations:  94%|█████████▍| 1394/1485 [00:42<00:02, 34.28it/s]

Reading stations:  94%|█████████▍| 1398/1485 [00:42<00:04, 17.42it/s]

Reading stations:  94%|█████████▍| 1401/1485 [00:43<00:04, 18.90it/s]

Reading stations:  95%|█████████▍| 1404/1485 [00:43<00:03, 20.44it/s]

Reading stations:  95%|█████████▍| 1408/1485 [00:43<00:03, 24.22it/s]

Reading stations:  95%|█████████▌| 1412/1485 [00:43<00:02, 24.85it/s]

Reading stations:  95%|█████████▌| 1415/1485 [00:43<00:02, 24.87it/s]

Reading stations:  96%|█████████▌| 1419/1485 [00:43<00:02, 27.22it/s]

Reading stations:  96%|█████████▌| 1422/1485 [00:43<00:02, 27.00it/s]

Reading stations:  96%|█████████▌| 1425/1485 [00:43<00:02, 22.56it/s]

Reading stations:  96%|█████████▌| 1428/1485 [00:44<00:02, 24.20it/s]

Reading stations:  96%|█████████▋| 1432/1485 [00:44<00:01, 26.92it/s]

Reading stations:  97%|█████████▋| 1435/1485 [00:44<00:01, 26.55it/s]

Reading stations:  97%|█████████▋| 1438/1485 [00:44<00:01, 26.30it/s]

Reading stations:  97%|█████████▋| 1441/1485 [00:44<00:01, 24.16it/s]

Reading stations:  97%|█████████▋| 1444/1485 [00:44<00:01, 22.41it/s]

Reading stations:  98%|█████████▊| 1448/1485 [00:44<00:01, 23.27it/s]

Reading stations:  98%|█████████▊| 1452/1485 [00:45<00:01, 26.59it/s]

Reading stations:  98%|█████████▊| 1455/1485 [00:45<00:01, 27.24it/s]

Reading stations:  98%|█████████▊| 1458/1485 [00:45<00:01, 26.02it/s]

Reading stations:  98%|█████████▊| 1461/1485 [00:45<00:00, 27.03it/s]

Reading stations:  99%|█████████▊| 1465/1485 [00:45<00:00, 28.10it/s]

Reading stations:  99%|█████████▉| 1470/1485 [00:45<00:00, 30.37it/s]

Reading stations:  99%|█████████▉| 1475/1485 [00:45<00:00, 34.92it/s]

Reading stations: 100%|█████████▉| 1479/1485 [00:45<00:00, 34.62it/s]

Reading stations: 100%|█████████▉| 1483/1485 [00:45<00:00, 35.72it/s]

Reading stations: 100%|██████████| 1485/1485 [00:46<00:00, 32.28it/s]

Merged 1,485 stations → 1,419,960 rows × 84 columns in 49 s

In [9]:
aeronet_raw

,site,Date(dd:mm:yyyy),Time(hh:mm:ss),Day_of_Year,AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,...,N[340-440_Angstrom_Exponent],N[440-675_Angstrom_Exponent[Polar]],Data_Quality_Level,AERONET_Instrument_Number,AERONET_Site_Name,Site_Latitude(Degrees),Site_Longitude(Degrees),Site_Elevation(m),PI,PI_Email
0,AAOT,04:10:2017,12:00:00,277,NaN,0.169420,NaN,0.227937,0.270857,NaN,...,0,0,lev20,1001,AAOT,45.3139,12.5083,10.0,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
1,AAOT,11:10:2017,12:00:00,284,NaN,0.121093,NaN,0.165021,0.201501,NaN,...,0,0,lev20,1001,AAOT,45.3139,12.5083,10.0,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
2,AAOT,12:10:2017,12:00:00,285,NaN,0.248953,NaN,0.338806,0.409216,NaN,...,0,0,lev20,1001,AAOT,45.3139,12.5083,10.0,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
3,AAOT,13:10:2017,12:00:00,286,NaN,0.270292,NaN,0.344527,0.402378,NaN,...,0,0,lev20,1001,AAOT,45.3139,12.5083,10.0,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
4,AAOT,14:10:2017,12:00:00,287,NaN,0.178536,NaN,0.242100,0.290174,NaN,...,0,0,lev20,1001,AAOT,45.3139,12.5083,10.0,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419955,Zvenigorod,09:10:2021,12:00:00,282,NaN,0.032274,0.038148,NaN,NaN,0.045768,...,15,0,lev20,132,Zvenigorod,55.6950,36.7750,200.0,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419956,Zvenigorod,10:10:2021,12:00:00,283,NaN,0.019934,0.026304,NaN,NaN,0.034218,...,33,0,lev20,132,Zvenigorod,55.6950,36.7750,200.0,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419957,Zvenigorod,11:10:2021,12:00:00,284,NaN,0.029062,0.039846,NaN,NaN,0.057453,...,6,0,lev20,132,Zvenigorod,55.6950,36.7750,200.0,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419958,Zvenigorod,15:10:2021,12:00:00,288,NaN,0.027265,0.037933,NaN,NaN,0.057122,...,1,0,lev20,132,Zvenigorod,55.6950,36.7750,200.0,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419959,Zvenigorod,18:10:2021,12:00:00,291,NaN,0.022290,0.028122,NaN,NaN,0.037910,...,6,0,lev20,132,Zvenigorod,55.6950,36.7750,200.0,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov

In [10]:
aeronet_raw.columns

Index(['site', 'Date(dd:mm:yyyy)', 'Time(hh:mm:ss)', 'Day_of_Year',
       'AOD_1640nm', 'AOD_1020nm', 'AOD_870nm', 'AOD_865nm', 'AOD_779nm',
       'AOD_675nm', 'AOD_667nm', 'AOD_620nm', 'AOD_560nm', 'AOD_555nm',
       'AOD_551nm', 'AOD_532nm', 'AOD_531nm', 'AOD_510nm', 'AOD_500nm',
       'AOD_490nm', 'AOD_443nm', 'AOD_440nm', 'AOD_412nm', 'AOD_400nm',
       'AOD_380nm', 'AOD_340nm', 'Precipitable_Water(cm)', 'AOD_681nm',
       'AOD_709nm', 'AOD_Empty', 'AOD_Empty.1', 'AOD_Empty.2', 'AOD_Empty.3',
       'AOD_Empty.4', '440-870_Angstrom_Exponent', '380-500_Angstrom_Exponent',
       '440-675_Angstrom_Exponent', '500-870_Angstrom_Exponent',
       '340-440_Angstrom_Exponent', '440-675_Angstrom_Exponent[Polar]',
       'N[AOD_1640nm]', 'N[AOD_1020nm]', 'N[AOD_870nm]', 'N[AOD_865nm]',
       'N[AOD_779nm]', 'N[AOD_675nm]', 'N[AOD_667nm]', 'N[AOD_620nm]',
       'N[AOD_560nm]', 'N[AOD_555nm]', 'N[AOD_551nm]', 'N[AOD_532nm]',
       'N[AOD_531nm]', 'N[AOD_510nm]', 'N[AOD_500nm]', 'N[AOD_490nm]',
       'N[AOD_443nm]', 'N[AOD_440nm]', 'N[AOD_412nm]', 'N[AOD_400nm]',
       'N[AOD_380nm]', 'N[AOD_340nm]', 'N[Precipitable_Water(cm)]',
       'N[AOD_681nm]', 'N[AOD_709nm]', 'N[AOD_Empty]', 'N[AOD_Empty].1',
       'N[AOD_Empty].2', 'N[AOD_Empty].3', 'N[AOD_Empty].4',
       'N[440-870_Angstrom_Exponent]', 'N[380-500_Angstrom_Exponent]',
       'N[440-675_Angstrom_Exponent]', 'N[500-870_Angstrom_Exponent]',
       'N[340-440_Angstrom_Exponent]', 'N[440-675_Angstrom_Exponent[Polar]]',
       'Data_Quality_Level', 'AERONET_Instrument_Number', 'AERONET_Site_Name',
       'Site_Latitude(Degrees)', 'Site_Longitude(Degrees)',
       'Site_Elevation(m)', 'PI', 'PI_Email'],
      dtype='object')

## 3 · Tidy into an agent-ready table

* keep AERONET's own column names; only replace characters that break pandas / SQL / DuckDB (`Precipitable_Water(cm)` → `Precipitable_Water_cm`, `Site_Latitude(Degrees)` → `Site_Latitude_Degrees`, `N[AOD_500nm]` → `N_AOD_500nm`, `440-870_Angstrom_Exponent` → `Angstrom_Exponent_440_870nm`)
* add a proper `datetime_utc` (and `date`, `year`, `month`) built from AERONET's `dd:mm:yyyy` + `hh:mm:ss` columns
* drop the placeholder `AOD_Empty` columns and any wavelength that is missing at every site
* one consistent column order: site → time → location → AOD → Ångström → water vapour → observation counts → contact

In [11]:
def clean_col(name: str) -> str:
    name = re.sub(r"(\d{3})-(\d{3})_Angstrom_Exponent", r"Angstrom_Exponent_\1_\2nm", name)
    name = name.replace("[Polar]", "_Polar")
    name = re.sub(r"[\(\[]", "_", name)
    name = re.sub(r"[\)\]]", "", name)
    name = re.sub(r"[^0-9A-Za-z_]", "_", name)
    return re.sub(r"_+", "_", name).strip("_")

In [12]:
df = aeronet_raw.copy()

In [13]:
# ── placeholder columns (pandas mangles the duplicated "AOD_Empty" header to AOD_Empty, AOD_Empty.1, …)
df = df.drop(columns=[c for c in df.columns if "AOD_Empty" in c])

In [14]:
# AERONET stamps every daily average at 12:00:00 UTC
df["datetime_utc"] = pd.to_datetime(df["Date(dd:mm:yyyy)"] + " " + df["Time(hh:mm:ss)"], format="%d:%m:%Y %H:%M:%S")
df = df.drop(columns=["Date(dd:mm:yyyy)", "Time(hh:mm:ss)"])

df["date"]  = df["datetime_utc"].dt.normalize()
df["year"]  = df["datetime_utc"].dt.year.astype("int16")
df["month"] = df["datetime_utc"].dt.month.astype("int8")

In [15]:
df.columns = [clean_col(c) for c in df.columns]

In [16]:
# AERONET repeats the site name in every row – make sure it matches the file header, then keep the original column
mismatch = (df["AERONET_Site_Name"] != df["site"]).sum()
print(f"site-name mismatches between header and rows: {mismatch}")
df = df.drop(columns=["site"])

site-name mismatches between header and rows: 0

In [17]:
# ── drop wavelengths that no site ever measured (all-NaN) -----------------------
all_nan = [c for c in df.columns if df[c].isna().all()]
if all_nan:
    print(f"dropping {len(all_nan)} all-NaN columns: {all_nan}")
    df = df.drop(columns=all_nan)

dropping 1 all-NaN columns: ['AOD_531nm']

In [18]:
# … and their (now meaningless) observation-count columns
df = df.drop(columns=[c for c in df.columns if c.startswith("N_") and c[2:] not in df.columns])

In [19]:
# ── dtypes ----------------------------------------------------------------------
for c in df.columns:
    if c.startswith("N_"):
        df[c] = df[c].astype("Int32")
df["AERONET_Site_Name"] = df["AERONET_Site_Name"].astype("string")
for c in ("PI", "PI_Email", "Data_Quality_Level"):
    if c in df.columns:
        df[c] = df[c].astype("string")

In [20]:
# ── column order ----------------------------------------------------------------
def _group(c):
    order = ["AERONET_Site_Name", "datetime_utc", "date", "year", "month", "Day_of_Year",
             "Site_Latitude_Degrees", "Site_Longitude_Degrees", "Site_Elevation_m"]
    if c in order:                       return (0, order.index(c))
    if c.startswith("AOD_"):             return (1, -int(re.search(r"(\d+)nm", c).group(1)))   # long → short wavelength, like AERONET
    if c.startswith("Angstrom_"):        return (2, c)
    if c.startswith("Precipitable_"):    return (3, c)
    if c.startswith("N_"):               return (4, c)
    return (5, c)

In [21]:
df = df[sorted(df.columns, key=_group)]
df = df.sort_values(["AERONET_Site_Name", "datetime_utc"], ignore_index=True)

In [22]:
aeronet = df
del df
print(f"{aeronet.shape[0]:,} rows × {aeronet.shape[1]} columns")
print(list(aeronet.columns))

1,419,960 rows × 73 columns
['AERONET_Site_Name', 'datetime_utc', 'date', 'year', 'month', 'Day_of_Year', 'Site_Latitude_Degrees', 'Site_Longitude_Degrees', 'Site_Elevation_m', 'AOD_1640nm', 'AOD_1020nm', 'AOD_870nm', 'AOD_865nm', 'AOD_779nm', 'AOD_709nm', 'AOD_681nm', 'AOD_675nm', 'AOD_667nm', 'AOD_620nm', 'AOD_560nm', 'AOD_555nm', 'AOD_551nm', 'AOD_532nm', 'AOD_510nm', 'AOD_500nm', 'AOD_490nm', 'AOD_443nm', 'AOD_440nm', 'AOD_412nm', 'AOD_400nm', 'AOD_380nm', 'AOD_340nm', 'Angstrom_Exponent_340_440nm', 'Angstrom_Exponent_380_500nm', 'Angstrom_Exponent_440_675nm', 'Angstrom_Exponent_440_675nm_Polar', 'Angstrom_Exponent_440_870nm', 'Angstrom_Exponent_500_870nm', 'Precipitable_Water_cm', 'N_AOD_1020nm', 'N_AOD_1640nm', 'N_AOD_340nm', 'N_AOD_380nm', 'N_AOD_400nm', 'N_AOD_412nm', 'N_AOD_440nm', 'N_AOD_443nm', 'N_AOD_490nm', 'N_AOD_500nm', 'N_AOD_510nm', 'N_AOD_532nm', 'N_AOD_551nm', 'N_AOD_555nm', 'N_AOD_560nm', 'N_AOD_620nm', 'N_AOD_667nm', 'N_AOD_675nm', 'N_AOD_681nm', 'N_AOD_709nm', 'N_AOD_779nm', 'N_AOD_865nm', 'N_AOD_870nm', 'N_Angstrom_Exponent_340_440nm', 'N_Angstrom_Exponent_380_500nm', 'N_Angstrom_Exponent_440_675nm', 'N_Angstrom_Exponent_440_675nm_Polar', 'N_Angstrom_Exponent_440_870nm', 'N_Angstrom_Exponent_500_870nm', 'N_Precipitable_Water_cm', 'AERONET_Instrument_Number', 'Data_Quality_Level', 'PI', 'PI_Email']

In [23]:
aeronet

,AERONET_Site_Name,datetime_utc,date,year,month,Day_of_Year,Site_Latitude_Degrees,Site_Longitude_Degrees,Site_Elevation_m,AOD_1640nm,...,N_Angstrom_Exponent_380_500nm,N_Angstrom_Exponent_440_675nm,N_Angstrom_Exponent_440_675nm_Polar,N_Angstrom_Exponent_440_870nm,N_Angstrom_Exponent_500_870nm,N_Precipitable_Water_cm,AERONET_Instrument_Number,Data_Quality_Level,PI,PI_Email
0,AAOT,2017-10-04 12:00:00,2017-10-04,2017,10,277,45.3139,12.5083,10.0,NaN,...,0,25,0,25,0,25,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
1,AAOT,2017-10-11 12:00:00,2017-10-11,2017,10,284,45.3139,12.5083,10.0,NaN,...,0,20,0,20,0,20,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
2,AAOT,2017-10-12 12:00:00,2017-10-12,2017,10,285,45.3139,12.5083,10.0,NaN,...,0,33,0,33,0,33,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
3,AAOT,2017-10-13 12:00:00,2017-10-13,2017,10,286,45.3139,12.5083,10.0,NaN,...,0,7,0,7,0,7,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
4,AAOT,2017-10-14 12:00:00,2017-10-14,2017,10,287,45.3139,12.5083,10.0,NaN,...,0,12,0,12,0,12,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419955,Zvenigorod,2021-10-09 12:00:00,2021-10-09,2021,10,282,55.6950,36.7750,200.0,NaN,...,15,15,0,15,15,15,132,lev20,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419956,Zvenigorod,2021-10-10 12:00:00,2021-10-10,2021,10,283,55.6950,36.7750,200.0,NaN,...,33,33,0,33,33,33,132,lev20,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419957,Zvenigorod,2021-10-11 12:00:00,2021-10-11,2021,10,284,55.6950,36.7750,200.0,NaN,...,6,6,0,6,6,6,132,lev20,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419958,Zvenigorod,2021-10-15 12:00:00,2021-10-15,2021,10,288,55.6950,36.7750,200.0,NaN,...,1,1,0,1,1,1,132,lev20,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov
1419959,Zvenigorod,2021-10-18 12:00:00,2021-10-18,2021,10,291,55.6950,36.7750,200.0,NaN,...,6,6,0,6,6,6,132,lev20,Pawan_Gupta_and_Elena_Lind,pawan.gupta@nasa.gov_and_elena.lind@nasa.gov

## 4 · Sanity checks

In [24]:
print(f"sites        : {aeronet['AERONET_Site_Name'].nunique():,}")
print(f"rows         : {len(aeronet):,}")
print(f"time range   : {aeronet['datetime_utc'].min()}  →  {aeronet['datetime_utc'].max()}")
print(f"duplicates   : {aeronet.duplicated(['AERONET_Site_Name', 'datetime_utc']).sum():,}  (site × datetime)")
print(f"memory       : {aeronet.memory_usage(deep=True).sum() / 1e6:,.0f} MB")

print("\nnon-null fraction per column:")
display((aeronet.notna().mean() * 100).round(1).rename("% non-null").to_frame().T)

display(aeronet.head())

sites        : 1,485
rows         : 1,419,960
time range   : 1993-05-14 12:00:00  →  2026-07-14 12:00:00

duplicates   : 0  (site × datetime)

memory       : 1,028 MB

non-null fraction per column:

,AERONET_Site_Name,datetime_utc,date,year,month,Day_of_Year,Site_Latitude_Degrees,Site_Longitude_Degrees,Site_Elevation_m,AOD_1640nm,...,N_Angstrom_Exponent_380_500nm,N_Angstrom_Exponent_440_675nm,N_Angstrom_Exponent_440_675nm_Polar,N_Angstrom_Exponent_440_870nm,N_Angstrom_Exponent_500_870nm,N_Precipitable_Water_cm,AERONET_Instrument_Number,Data_Quality_Level,PI,PI_Email
% non-null,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,53.5,...,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0

,AERONET_Site_Name,datetime_utc,date,year,month,Day_of_Year,Site_Latitude_Degrees,Site_Longitude_Degrees,Site_Elevation_m,AOD_1640nm,...,N_Angstrom_Exponent_380_500nm,N_Angstrom_Exponent_440_675nm,N_Angstrom_Exponent_440_675nm_Polar,N_Angstrom_Exponent_440_870nm,N_Angstrom_Exponent_500_870nm,N_Precipitable_Water_cm,AERONET_Instrument_Number,Data_Quality_Level,PI,PI_Email
0,AAOT,2017-10-04 12:00:00,2017-10-04,2017,10,277,45.3139,12.5083,10.0,NaN,...,0,25,0,25,0,25,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
1,AAOT,2017-10-11 12:00:00,2017-10-11,2017,10,284,45.3139,12.5083,10.0,NaN,...,0,20,0,20,0,20,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
2,AAOT,2017-10-12 12:00:00,2017-10-12,2017,10,285,45.3139,12.5083,10.0,NaN,...,0,33,0,33,0,33,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
3,AAOT,2017-10-13 12:00:00,2017-10-13,2017,10,286,45.3139,12.5083,10.0,NaN,...,0,7,0,7,0,7,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu
4,AAOT,2017-10-14 12:00:00,2017-10-14,2017,10,287,45.3139,12.5083,10.0,NaN,...,0,12,0,12,0,12,1001,lev20,Giuseppe_Zibordi,giuseppe.zibordi@eoscience.eu

## 5 · Export to `DATA/PROCESSED/`

One file: `AERONET_AOD_L2_Daily_V3.parquet` — the full merged table, one row per site × day.

In [25]:
aeronet.to_parquet(OUT_PARQUET, index=False, engine="pyarrow", compression="zstd")
print(f"wrote {OUT_PARQUET}  ({OUT_PARQUET.stat().st_size / 1e6:,.0f} MB, {len(aeronet):,} rows × {aeronet.shape[1]} columns)")

wrote /home/ubuntu/ai_for_aeronet/DATA/PROCESSED/AERONET_AOD_L2_Daily_V3.parquet  (163 MB, 1,419,960 rows × 73 columns)

### Output schema (data dictionary for the agent's skill / system prompt)

Column names are AERONET's own, with only `( ) [ ] -` replaced by `_` so they work in pandas / SQL. Unit suffixes come from AERONET's headers.

| column | original AERONET header | unit | meaning |
|---|---|---|---|
| `AERONET_Site_Name` | `AERONET_Site_Name` | – | site name (string) |
| `datetime_utc`, `date`, `year`, `month` | *derived from* `Date(dd:mm:yyyy)` + `Time(hh:mm:ss)` | UTC | daily averages are stamped 12:00:00 UTC |
| `Day_of_Year` | `Day_of_Year` | day | 1–366 |
| `Site_Latitude_Degrees`, `Site_Longitude_Degrees` | `Site_Latitude(Degrees)`, `Site_Longitude(Degrees)` | decimal degrees | site location (WGS84) |
| `Site_Elevation_m` | `Site_Elevation(m)` | metres | site elevation above sea level |
| `AOD_<λ>nm` | `AOD_<λ>nm` | unitless | aerosol optical depth at wavelength λ nanometres; NaN = not measured / did not pass Level 2.0 screening |
| `Angstrom_Exponent_<λ1>_<λ2>nm` | `<λ1>-<λ2>_Angstrom_Exponent` | unitless | Ångström exponent computed between λ1 and λ2 nm (`_Polar` = polar-instrument variant) |
| `Precipitable_Water_cm` | `Precipitable_Water(cm)` | centimetres | total column water vapour |
| `N_<column>` | `N[<column>]` | count | number of Level 2.0 measurements averaged into that daily value (0 ⇒ value is NaN) |
| `Data_Quality_Level` | `Data_Quality_Level` | – | always `lev20` |
| `AERONET_Instrument_Number` | `AERONET_Instrument_Number` | – | CIMEL sun-photometer id |
| `PI`, `PI_Email` | *file header line 5* | – | site principal investigator (AERONET data-use policy: contact / acknowledge) |

Units reference: <https://aeronet.gsfc.nasa.gov/new_web/units.html>